baseURL = 'https://phcurado.github.io/'
languageCode = 'en-us'
title = 'phcurado'
theme = 'paper'

[params]
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'github.com/phcurado'
  rss = true                                # show rss icon

  # home page profile
  name = 'Paulo Curado'
  bio = 'Software Engineer'


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon